### ISSUE TITLE
Annotate_bismark_cov.py error

### ISSUE THREAD

**Issue by jarcasariego** [lyijin/working_with_dna_meth#2]
Hi Dr. Liew, 
Here I am again. I was able to get the GFF3 file fixed and apparently running parse_gff3.py with no errors. However, I'm getting errors from the Annotate_bismark_cov.py code:

```
Traceback (most recent call last):
  File "./annotate_bismark_cov.py", line 203, in <module>
    gene_info[s] = np.zeros(sequence_lengths[s], np.uint32)
KeyError: 'Sc0000000'
```

I checked the code and the GFF file and I'm not very clear of what the problem might be. This is the biggest scaffold and has 1331 features. Could it be that my GFF3 has no 'intron' track? Also, I noticed that in the GFF exons are numbered starting at exon 0.  

This is how my GFF3 is structured as from the output of GFFExaminer:

```
{('maker', 'gene'): [('maker', 'mRNA')],
 ('maker', 'mRNA'): [('maker', 'CDS'),
                     ('maker', 'exon'),
                     ('maker', 'five_prime_UTR'),
                     ('maker', 'three_prime_UTR')]}
'gff_source': {('maker',): 364679},
 'gff_source_type': {('maker', 'CDS'): 141898,
                     ('maker', 'exon'): 149031,
                     ('maker', 'five_prime_UTR'): 11501,
                     ('maker', 'gene'): 24739,
                     ('maker', 'mRNA'): 24739,
                     ('maker', 'three_prime_UTR'): 12771},
 'gff_type': {('CDS',): 141898,
              ('exon',): 149031,
              ('five_prime_UTR',): 11501,
              ('gene',): 24739,
              ('mRNA',): 24739,
              ('three_prime_UTR',): 12771}}
```

I'm sorry for the stolen time, but could you give me a hand with that?

**Comment by lyijin** [comment]
hm, that's a strange place to be crashing at.

there are two dictionaries in the line where the crash happened, so i'm not entirely sure whether it's a gff parsing error, or whether the ``sequence_lengths`` dict had problems.

fortunately in python, debugging is easy. run the script with an ``-i`` in it (``python3 -i annotate_bismark_cov.py <arguments>``)

when it crashes, try to view the contents of both dicts. don't panic if too many things appear on your screen, just mash CTRL+C and you'd be back on safer shores.

to see contents
``>>> sequence_lengths``

to check whether a key exists in a dict
``>>> 'Sc0000000' in sequence_lengths``

once you identify the problematic dict, debug as much as you can, let me know if you still need help.

**Comment by jarcasariego** [comment]
Fixed it!!! Thanks so much. The issue was about the naming of the scaffold when `parse_fasta.py` create the annot component of sequence_lengths. Since the genome I used has a different header for the sequences I had to modify the code to modify the string before creating the annot component. 

Thanks very much for the help. I'll get to the fun part now. 

Cheers, 

Javier
